server:
  port: 8081

spring:
    application:
        name: kunfind-service-client
        #配置rabbitmq服务器
    rabbitmq:
        host: 192.168.1.79
        port: 5672
        username: root
        password: 123456
        virtual-host: /
      #redis配置
    redis:
        hostName: 192.168.1.79
        port: 6379
        #password:
        pool:
          max-active: 8
          max-wait: 1
          max-idle: 8
          min-idle: 0
        timeout: 0

#配置springcloud注册
eureka:
    instance:
      metadataMap:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      hostname: localhost
        # 不需要检索服务
      register-with-eureka: false
        # 不向注册中心注册自己
      fetch-registry: false
    #client:
     #   serviceUrl:
          #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #    defaultZone: http://localhost：8080/eureka/
    client:
      serviceUrl:
        defaultZone: http://root:123456@${eureka.instance.hostname}:8080/eureka/
              #defaultZone: http://localhost：8080/eureka/
