server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/testspring
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    application:
        name: kunfind-service
    #126邮箱
    mail:
        host: smtp.126.com
        username: goodlook0123@126.com
        password: dong#$123321
        properties:
            mail:
              auth: true
              starttls:
                 enable: true
                 required: true
#rabbitmq监听地址账号和密码
    rabbitmq:
        host: localhost
        #15672是控制台灯api端口
        port: 5672
        username: root
        password: 123456
      #redis配置
    redis:
        hostName: localhost
        port: 6379
        #password:
        pool:
          max-active: 8
          max-wait: 1
          max-idle: 8
          min-idle: 0
        timeout: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springboot.caoqing.bean

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#配置springcloud注册
eureka:
    instance:
      #metadataMap:
        #instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      hostname: localhost
        # 不需要检索服务
      register-with-eureka: false
        # 不向注册中心注册自己
      fetch-registry: false
    client:
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
              #defaultZone: http://localhost：8080/eureka/
security:
    basic:
      enabled: true
    user:
      name: root
      password: 123456

